<a href="https://colab.research.google.com/github/mishkatnaveed14/pandas/blob/main/pandas_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# Task # 1
data = {
    "Name" : ["Ali","Sara","Ahmad","Ayesha","Zain"],
     "Marks" : [70,85,60,95,45]
    }
print("Student Data:")
df = pd.DataFrame(data)
print(df)
print("\nAverage Marks:")
print(df["Marks"].mean())
print("\nMaximum Marks:")
print(df["Marks"].max())
print("\nMinimum Marks:")
print(df["Marks"].min())
print("\n Total students:")
print(df["Name"].count())

Student Data:
     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmad     60
3  Ayesha     95
4    Zain     45

Average Marks:
71.0

Maximum Marks:
95

Minimum Marks:
45

 Total students:
5

In [ ]:
# task # 2
greater_marks = df[df["Marks"] >= 50]
print("Students with marks greater than or equal to 50:")
print(greater_marks)
less_marks = df[df["Marks"] <= 50]
print("\nStudents with marks less than or equal to 50: ")
print(less_marks)

Students with marks greater than or equal to 50:
     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmad     60
3  Ayesha     95

Students with marks less than or equal to 50:
   Name  Marks
4  Zain     45

In [ ]:
# task # 3
df["City"] = ["Karachi", "Lahore", "Karachi", "Islamabad","Lahore"]
df
karachi_students = df[df["City"] == "Karachi"]
print("Karachi Students:")
print(karachi_students)
df

Karachi Students:
    Name  Marks     City
0    Ali     70  Karachi
2  Ahmad     60  Karachi

     Name  Marks       City
0     Ali     70    Karachi
1    Sara     85     Lahore
2   Ahmad     60    Karachi
3  Ayesha     95  Islamabad
4    Zain     45     Lahore

In [ ]:
# task # 4
data = {
    "Name" : ["Ali","Sara","Ahmad","Ayesha","Zain"],
     "Marks" : [70,85,60,95,45],
"Course" : ["AI","Web","AI","AI","Web"]
    }
df = pd.DataFrame(data)
average_marks = df.groupby("Course")["Marks"].mean()
print("Average Marks by Course:")
print(average_marks)
print("\nStudent Data:")
df

Average Marks by Course:
Course
AI     75.0
Web    65.0
Name: Marks, dtype: float64

Student Data:

     Name  Marks Course
0     Ali     70     AI
1    Sara     85    Web
2   Ahmad     60     AI
3  Ayesha     95     AI
4    Zain     45    Web

In [ ]:
# task # 5
data = {
  "Name" : ["Ali","Sara","Ahmad","Ayesha","Zain"],
  "Marks" : [80,None,70,None,90]
}
df = pd.DataFrame(data)
null_values = df.isnull().sum()
print("Null Values:")
print(null_values)
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df

Null Values:
Name     0
Marks    2
dtype: int64

     Name  Marks
0     Ali   80.0
1    Sara   80.0
2   Ahmad   70.0
3  Ayesha   80.0
4    Zain   90.0