<a href="https://colab.research.google.com/github/mishkatnaveed14/pandas/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
#READ A DATA SET
df = pd.read_csv("/content/Social_media_impact_on_life.csv")
df
# print(df)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
# CREATING A DATA FRAME
data = pd.DataFrame(df)
data
# print(data)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
# VEIWING DATA:
df.head(1)
df.tail(1)
# print(df.head(1))
# print(df.tail(1))
print(" DATAFRAME Information ==>", df.info())
print("\nAGE and STUDENT_ID ====>> \n",df[["Age","Student_ID"]])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   4500 non-null   object
 1   Age                          4500 non-null   int64
 2   Gender                       4500 non-null   object
 3   Academic_Level               4500 non-null   object
 4   Primary_Platform             4500 non-null   object
 5   Daily_Usage_Hours            4500 non-null   float64
 6   Weekend_Extra_Hours          4500 non-null   float64
 7   Device_Type                  4500 non-null   object
 8   Sleep_Duration_Hours         4500 non-null   float64
 9   Sleep_Quality_Score          4500 non-null   int64
 10  Late_Night_Usage             4500 non-null   bool
 11  Social_Comparison_Frequency  4500 non-null   object
 12  Perceived_Stress_Score       4454 non-null   float64
 13  Mental_Health_Index          4500 non-null   int64
 14  Academic_Performance_GPA     4415 non-null   float64
 15  Overall_Impact               4500 non-null   object
dtypes: bool(1), float64(5), int64(3), object(7)
memory usage: 531.9+ KB
 DATAFRAME Information ==> None

AGE and STUDENT_ID ====>>
       Age   Student_ID
0      19  STU_2024000
1      19  STU_2024001
2      17  STU_2024002
3      16  STU_2024003
4      17  STU_2024004
...   ...          ...
4495   16  STU_2028495
4496   19  STU_2028496
4497   19  STU_2028497
4498   16  STU_2028498
4499   24  STU_2028499

[4500 rows x 2 columns]

In [ ]:
# SHAPE
print("\n shape ==>",df.shape)
print("\n Random Data ==> ")
df.sample()

 shape ==> (4500, 16)

 Random Data ==>

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
1739,STU_2025739,20,Male,Undergraduate,YouTube,3.9,1.5,Smartphone,7.0,3,True,Rarely,13.0,83,4.0,Beneficial

In [ ]:
# COLOUMNS:
df.columns
# print(df.columns)

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Primary_Platform',
       'Daily_Usage_Hours', 'Weekend_Extra_Hours', 'Device_Type',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score', 'Late_Night_Usage',
       'Social_Comparison_Frequency', 'Perceived_Stress_Score',
       'Mental_Health_Index', 'Academic_Performance_GPA', 'Overall_Impact'],
      dtype='object')

In [ ]:
# DATATYPES
df.dtypes

Student_ID                      object
Age                              int64
Gender                          object
Academic_Level                  object
Primary_Platform                object
Daily_Usage_Hours              float64
Weekend_Extra_Hours            float64
Device_Type                     object
Sleep_Duration_Hours           float64
Sleep_Quality_Score              int64
Late_Night_Usage                  bool
Social_Comparison_Frequency     object
Perceived_Stress_Score         float64
Mental_Health_Index              int64
Academic_Performance_GPA       float64
Overall_Impact                  object
dtype: object

In [ ]:
# selecting columns
print("selecting column data: \n",df["Sleep_Duration_Hours"])
# selecting multiple columns
print("selecting multiple column data: \n""",df[["Age","Gender"]])

selecting column data:
 0       5.9
1       7.9
2       5.2
3       7.6
4       7.6
       ...
4495    7.8
4496    6.6
4497    6.0
4498    7.1
4499    6.8
Name: Sleep_Duration_Hours, Length: 4500, dtype: float64
selecting multiple column data:
       Age  Gender
0      19  Female
1      19  Female
2      17  Female
3      16  Female
4      17    Male
...   ...     ...
4495   16    Male
4496   19  Female
4497   19    Male
4498   16    Male
4499   24    Male

[4500 rows x 2 columns]

In [ ]:
# STATSTICAL SUMMARY :
# print(df.describe())
df.describe()

,Age,Daily_Usage_Hours,Weekend_Extra_Hours,Sleep_Duration_Hours,Sleep_Quality_Score,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA
count,4500.000000,4500.000000,4500.000000,4500.000000,4500.000000,4454.000000,4500.000000,4415.000000
mean,18.703333,5.295933,1.796844,6.701333,2.472000,13.512124,79.873111,3.429282
std,1.981182,2.604497,0.699245,1.189998,1.030484,7.072859,12.876044,0.392662
min,15.000000,0.900000,0.000000,3.000000,1.000000,0.000000,32.000000,1.900000
25%,17.000000,3.400000,1.300000,6.000000,2.000000,9.000000,72.000000,3.200000
50%,19.000000,4.700000,1.800000,6.800000,3.000000,13.000000,82.000000,3.460000
75%,20.000000,6.600000,2.300000,7.500000,3.000000,18.000000,89.000000,3.720000
max,26.000000,14.000000,4.500000,10.500000,5.000000,40.000000,98.000000,4.000000

In [ ]:
#  Selecting Rows — loc and iloc
# LOC
print(df.loc[2])
df.loc[2,"Age"]
# ILOC
print(df.iloc[0,1])

Student_ID                     STU_2024002
Age                                     17
Gender                              Female
Academic_Level                 High School
Primary_Platform                    TikTok
Daily_Usage_Hours                     10.9
Weekend_Extra_Hours                    1.7
Device_Type                     Smartphone
Sleep_Duration_Hours                   5.2
Sleep_Quality_Score                      1
Late_Night_Usage                      True
Social_Comparison_Frequency     Frequently
Perceived_Stress_Score                18.0
Mental_Health_Index                     70
Academic_Performance_GPA               3.0
Overall_Impact                     Neutral
Name: 2, dtype: object
19

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
# Filtering Data
data = pd.read_csv("/content/Social_media_impact_on_life.csv")
data
print("You're under 18")
data[data['Age']< 18]

You're under 18

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Smartphone,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
5,STU_2024005,16,Male,High School,TikTok,6.2,1.6,Smartphone,5.9,1,False,Rarely,10.0,66,3.21,Beneficial
10,STU_2024010,15,Female,High School,TikTok,4.4,1.9,Smartphone,5.8,2,False,Frequently,11.0,83,3.22,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4483,STU_2028483,17,Female,High School,TikTok,5.3,2.2,Smartphone,6.5,3,True,Frequently,13.0,82,3.02,Beneficial
4487,STU_2028487,17,Prefer not to say,High School,Instagram,8.8,2.5,Smartphone,6.2,1,True,Frequently,21.0,68,3.50,Beneficial
4494,STU_2028494,16,Male,High School,YouTube,5.2,1.6,Smartphone,5.7,3,True,Sometimes,24.0,77,3.31,Neutral
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial

In [ ]:
data['Age'].head()==[24,45,67,89,16]
data
print(f"you're adult")
data[data['Age'] > 18]

you're adult

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
6,STU_2024006,20,Male,Undergraduate,TikTok,5.6,1.8,Smartphone,8.3,3,False,Sometimes,10.0,88,3.72,Beneficial
7,STU_2024007,19,Female,Undergraduate,TikTok,1.2,2.4,Smartphone,8.1,5,False,Always,6.0,95,3.37,Beneficial
11,STU_2024011,20,Male,Undergraduate,LinkedIn,7.8,1.4,Smartphone,7.2,2,True,Sometimes,17.0,76,3.08,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4490,STU_2028490,19,Male,Undergraduate,TikTok,4.0,1.8,Smartphone,6.3,3,False,Sometimes,13.0,74,4.00,Beneficial
4492,STU_2028492,22,Male,Postgraduate,Snapchat,3.6,2.5,Smartphone,7.0,4,True,Frequently,11.0,92,3.42,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
# updating values
data.loc[0,"Age"] = 18
data
data.loc[2,"Device_Type"] = "Electronics"
data

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,18,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Electronics,5.2,1,True,Frequently,18.0,70,3.00,Neutral
3,STU_2024003,16,Female,High School,YouTube,6.0,2.3,Tablet,7.6,4,True,Sometimes,15.0,82,3.42,Beneficial
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
# deleting rows or column
data.drop("Age",axis=1)
data.drop("Gender",axis=1)
data.drop(3)

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,18,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial
2,STU_2024002,17,Female,High School,TikTok,10.9,1.7,Electronics,5.2,1,True,Frequently,18.0,70,3.00,Neutral
4,STU_2024004,17,Male,High School,LinkedIn,3.3,2.6,Smartphone,7.6,4,True,Never,16.0,84,3.41,Beneficial
5,STU_2024005,16,Male,High School,TikTok,6.2,1.6,Smartphone,5.9,1,False,Rarely,10.0,66,3.21,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,STU_2028495,16,Male,High School,YouTube,5.8,1.2,Smartphone,7.8,3,True,Sometimes,11.0,79,2.85,Beneficial
4496,STU_2028496,19,Female,Undergraduate,LinkedIn,3.8,3.0,Smartphone,6.6,3,False,Frequently,9.0,83,3.37,Beneficial
4497,STU_2028497,19,Male,Undergraduate,Instagram,7.7,1.1,Smartphone,6.0,2,True,Frequently,13.0,73,3.16,Beneficial
4498,STU_2028498,16,Male,High School,LinkedIn,4.6,3.3,Laptop/PC,7.1,3,False,Sometimes,22.0,87,3.50,Beneficial
4499,STU_2028499,24,Male,Undergraduate,Instagram,1.8,2.1,Smartphone,6.8,3,True,Frequently,10.0,98,3.73,Beneficial

In [ ]:
# tu find nan values
data.dropna()
data.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Primary_Platform                0
Daily_Usage_Hours               0
Weekend_Extra_Hours             0
Device_Type                     0
Sleep_Duration_Hours            0
Sleep_Quality_Score             0
Late_Night_Usage                0
Social_Comparison_Frequency     0
Perceived_Stress_Score         46
Mental_Health_Index             0
Academic_Performance_GPA       85
Overall_Impact                  0
dtype: int64

In [ ]:
data.sort_values("Age")

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
10,STU_2024010,15,Female,High School,TikTok,4.4,1.9,Smartphone,5.8,2,False,Frequently,11.0,83,3.22,Beneficial
4480,STU_2028480,15,Female,High School,Instagram,5.0,2.3,Tablet,8.8,4,True,Frequently,13.0,87,3.69,Beneficial
2167,STU_2026167,15,Female,High School,Reddit,6.8,1.9,Smartphone,5.0,1,True,Rarely,23.0,66,2.88,Neutral
2345,STU_2026345,15,Female,High School,TikTok,3.8,1.0,Smartphone,8.9,4,True,Sometimes,1.0,98,3.67,Beneficial
50,STU_2024050,15,Female,High School,TikTok,8.6,1.0,Smartphone,6.4,1,True,Rarely,11.0,66,3.38,Beneficial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,STU_2025419,26,Female,Postgraduate,Instagram,3.9,1.4,Laptop/PC,8.3,3,False,Rarely,9.0,87,3.84,Beneficial
1240,STU_2025240,26,Male,Postgraduate,YouTube,9.2,1.5,Smartphone,4.8,1,True,Sometimes,NaN,68,2.83,Neutral
368,STU_2024368,26,Female,Postgraduate,TikTok,3.9,1.7,Smartphone,6.6,1,True,Never,11.0,73,3.26,Beneficial
1255,STU_2025255,26,Female,Postgraduate,Instagram,8.6,1.4,Smartphone,5.7,2,True,Sometimes,9.0,73,3.34,Beneficial
2244,STU_2026244,26,Prefer not to say,Undergraduate,Instagram,5.1,2.7,Smartphone,6.7,3,True,Rarely,13.0,76,3.56,Beneficial

In [ ]:
data.groupby("Age").count()

,Student_ID,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
Age,,,,,,,,,,,,,,,
15,164,164,164,164,164,164,164,164,164,164,164,163,164,158,164
16,340,340,340,340,340,340,340,340,340,340,340,338,340,332,340
17,716,716,716,716,716,716,716,716,716,716,716,708,716,708,716
18,1029,1029,1029,1029,1029,1029,1029,1029,1029,1029,1029,1018,1029,1007,1029
19,901,901,901,901,901,901,901,901,901,901,901,895,901,884,901
20,630,630,630,630,630,630,630,630,630,630,630,625,630,617,630
21,356,356,356,356,356,356,356,356,356,356,356,347,356,350,356
22,178,178,178,178,178,178,178,178,178,178,178,177,178,175,178
23,85,85,85,85,85,85,85,85,85,85,85,84,85,84,85
24,50,50,50,50,50,50,50,50,50,50,50,49,50,49,50
25,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
26,29,29,29,29,29,29,29,29,29,29,29,28,29,29,29